[package]
name = "singularities-vrf"
version = "0.1.0"
description = "Provably fair hack resolution via MagicBlock VRF"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "singularities_vrf"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { version = "0.31.1", features = ["init-if-needed"] }
ephemeral-rollups-sdk = { version = "0.6.5", features = ["anchor"] }
ephemeral-vrf-sdk = { version = "0.2.1", features = ["anchor"] }
